/*
 Dynamsoft JavaScript Library
 Product: Dynamsoft Web Twain
 Web Site: http://www.dynamsoft.com

 Copyright 2021, Dynamsoft Corporation 
 Author: Dynamsoft Support Team
 Module: image io js
 Version: 1.7.1
 @20210511140932.708000+480
 Dynamsoft.WasmEnv.busy() && */
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};
$jscomp.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global,a];for(var b=0;b<a.length;++b){var d=a[b];if(d&&d.Math==Math)return d}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,d){a!=Array.prototype&&a!=Object.prototype&&(a[b]=d.value)};$jscomp.polyfill=function(a,b,d,e){if(b){d=$jscomp.global;a=a.split(".");for(e=0;e<a.length-1;e++){var c=a[e];c in d||(d[c]={});d=d[c]}a=a[a.length-1];e=d[a];b=b(e);b!=e&&null!=b&&$jscomp.defineProperty(d,a,{configurable:!0,writable:!0,value:b})}};$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(a){function b(){this.batch_=null}function d(a){return a instanceof c?a:new c(function(c,b){c(a)})}if(a&&!$jscomp.FORCE_POLYFILL_PROMISE)return a;b.prototype.asyncExecute=function(a){if(null==this.batch_){this.batch_=[];var c=this;this.asyncExecuteFunction(function(){c.executeBatch_()})}this.batch_.push(a)};var e=$jscomp.global.setTimeout;b.prototype.asyncExecuteFunction=function(a){e(a,0)};b.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var a=
this.batch_;this.batch_=[];for(var c=0;c<a.length;++c){var b=a[c];a[c]=null;try{b()}catch(l){this.asyncThrow_(l)}}}this.batch_=null};b.prototype.asyncThrow_=function(a){this.asyncExecuteFunction(function(){throw a;})};var c=function(a){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var c=this.createResolveAndReject_();try{a(c.resolve,c.reject)}catch(h){c.reject(h)}};c.prototype.createResolveAndReject_=function(){function a(a){return function(f){b||(b=!0,a.call(c,f))}}var c=this,b=!1;
return{resolve:a(this.resolveTo_),reject:a(this.reject_)}};c.prototype.resolveTo_=function(a){if(a===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(a instanceof c)this.settleSameAsPromise_(a);else{a:switch(typeof a){case "object":var b=null!=a;break a;case "function":b=!0;break a;default:b=!1}b?this.resolveToNonPromiseObj_(a):this.fulfill_(a)}};c.prototype.resolveToNonPromiseObj_=function(a){var c=void 0;try{c=a.then}catch(h){this.reject_(h);return}"function"==typeof c?
this.settleSameAsThenable_(c,a):this.fulfill_(a)};c.prototype.reject_=function(a){this.settle_(2,a)};c.prototype.fulfill_=function(a){this.settle_(1,a)};c.prototype.settle_=function(a,c){if(0!=this.state_)throw Error("Cannot settle("+a+", "+c+"): Promise already settled in state"+this.state_);this.state_=a;this.result_=c;this.executeOnSettledCallbacks_()};c.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var a=0;a<this.onSettledCallbacks_.length;++a)f.asyncExecute(this.onSettledCallbacks_[a]);
this.onSettledCallbacks_=null}};var f=new b;c.prototype.settleSameAsPromise_=function(a){var c=this.createResolveAndReject_();a.callWhenSettled_(c.resolve,c.reject)};c.prototype.settleSameAsThenable_=function(a,c){var b=this.createResolveAndReject_();try{a.call(c,b.resolve,b.reject)}catch(l){b.reject(l)}};c.prototype.then=function(a,b){function f(a,c){return"function"==typeof a?function(c){try{d(a(c))}catch(q){e(q)}}:c}var d,e,k=new c(function(a,c){d=a;e=c});this.callWhenSettled_(f(a,d),f(b,e));return k};
c.prototype.catch=function(a){return this.then(void 0,a)};c.prototype.callWhenSettled_=function(a,c){function b(){switch(d.state_){case 1:a(d.result_);break;case 2:c(d.result_);break;default:throw Error("Unexpected state: "+d.state_);}}var d=this;null==this.onSettledCallbacks_?f.asyncExecute(b):this.onSettledCallbacks_.push(b)};c.resolve=d;c.reject=function(a){return new c(function(c,b){b(a)})};c.race=function(a){return new c(function(c,b){for(var f=$jscomp.makeIterator(a),e=f.next();!e.done;e=f.next())d(e.value).callWhenSettled_(c,
b)})};c.all=function(a){var b=$jscomp.makeIterator(a),f=b.next();return f.done?d([]):new c(function(a,c){function e(c){return function(b){k[c]=b;g--;0==g&&a(k)}}var k=[],g=0;do k.push(void 0),g++,d(f.value).callWhenSettled_(e(k.length-1),c),f=b.next();while(!f.done)})};return c},"es6","es3");$jscomp.SYMBOL_PREFIX="jscomp_symbol_";$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};
$jscomp.SymbolClass=function(a,b){this.$jscomp$symbol$id_=a;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:b})};$jscomp.SymbolClass.prototype.toString=function(){return this.$jscomp$symbol$id_};$jscomp.Symbol=function(){function a(d){if(this instanceof a)throw new TypeError("Symbol is not a constructor");return new $jscomp.SymbolClass($jscomp.SYMBOL_PREFIX+(d||"")+"_"+b++,d)}var b=0;return a}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("Symbol.iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}});$jscomp.initSymbolIterator=function(){}};
$jscomp.initSymbolAsyncIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.asyncIterator;a||(a=$jscomp.global.Symbol.asyncIterator=$jscomp.global.Symbol("Symbol.asyncIterator"));$jscomp.initSymbolAsyncIterator=function(){}};$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.underscoreProtoCanBeSet=function(){var a={a:!0},b={};try{return b.__proto__=a,b.a}catch(d){}return!1};
$jscomp.setPrototypeOf="function"==typeof Object.setPrototypeOf?Object.setPrototypeOf:$jscomp.underscoreProtoCanBeSet()?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null;$jscomp.generator={};$jscomp.generator.ensureIteratorResultIsObject_=function(a){if(!(a instanceof Object))throw new TypeError("Iterator result "+a+" is not an object");};
$jscomp.generator.Context=function(){this.isRunning_=!1;this.yieldAllIterator_=null;this.yieldResult=void 0;this.nextAddress=1;this.finallyAddress_=this.catchAddress_=0;this.finallyContexts_=this.abruptCompletion_=null};$jscomp.generator.Context.prototype.start_=function(){if(this.isRunning_)throw new TypeError("Generator is already running");this.isRunning_=!0};$jscomp.generator.Context.prototype.stop_=function(){this.isRunning_=!1};
$jscomp.generator.Context.prototype.jumpToErrorHandler_=function(){this.nextAddress=this.catchAddress_||this.finallyAddress_};$jscomp.generator.Context.prototype.next_=function(a){this.yieldResult=a};$jscomp.generator.Context.prototype.throw_=function(a){this.abruptCompletion_={exception:a,isException:!0};this.jumpToErrorHandler_()};$jscomp.generator.Context.prototype.return=function(a){this.abruptCompletion_={return:a};this.nextAddress=this.finallyAddress_};
$jscomp.generator.Context.prototype.jumpThroughFinallyBlocks=function(a){this.abruptCompletion_={jumpTo:a};this.nextAddress=this.finallyAddress_};$jscomp.generator.Context.prototype.yield=function(a,b){this.nextAddress=b;return{value:a}};$jscomp.generator.Context.prototype.yieldAll=function(a,b){a=$jscomp.makeIterator(a);var d=a.next();$jscomp.generator.ensureIteratorResultIsObject_(d);if(d.done)this.yieldResult=d.value,this.nextAddress=b;else return this.yieldAllIterator_=a,this.yield(d.value,b)};
$jscomp.generator.Context.prototype.jumpTo=function(a){this.nextAddress=a};$jscomp.generator.Context.prototype.jumpToEnd=function(){this.nextAddress=0};$jscomp.generator.Context.prototype.setCatchFinallyBlocks=function(a,b){this.catchAddress_=a;void 0!=b&&(this.finallyAddress_=b)};$jscomp.generator.Context.prototype.setFinallyBlock=function(a){this.catchAddress_=0;this.finallyAddress_=a||0};$jscomp.generator.Context.prototype.leaveTryBlock=function(a,b){this.nextAddress=a;this.catchAddress_=b||0};
$jscomp.generator.Context.prototype.enterCatchBlock=function(a){this.catchAddress_=a||0;a=this.abruptCompletion_.exception;this.abruptCompletion_=null;return a};$jscomp.generator.Context.prototype.enterFinallyBlock=function(a,b,d){d?this.finallyContexts_[d]=this.abruptCompletion_:this.finallyContexts_=[this.abruptCompletion_];this.catchAddress_=a||0;this.finallyAddress_=b||0};
$jscomp.generator.Context.prototype.leaveFinallyBlock=function(a,b){b=this.finallyContexts_.splice(b||0)[0];if(b=this.abruptCompletion_=this.abruptCompletion_||b){if(b.isException)return this.jumpToErrorHandler_();void 0!=b.jumpTo&&this.finallyAddress_<b.jumpTo?(this.nextAddress=b.jumpTo,this.abruptCompletion_=null):this.nextAddress=this.finallyAddress_}else this.nextAddress=a};$jscomp.generator.Context.prototype.forIn=function(a){return new $jscomp.generator.Context.PropertyIterator(a)};
$jscomp.generator.Context.PropertyIterator=function(a){this.object_=a;this.properties_=[];for(var b in a)this.properties_.push(b);this.properties_.reverse()};$jscomp.generator.Context.PropertyIterator.prototype.getNext=function(){for(;0<this.properties_.length;){var a=this.properties_.pop();if(a in this.object_)return a}return null};$jscomp.generator.Engine_=function(a){this.context_=new $jscomp.generator.Context;this.program_=a};
$jscomp.generator.Engine_.prototype.next_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_.next,a,this.context_.next_);this.context_.next_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.return_=function(a){this.context_.start_();var b=this.context_.yieldAllIterator_;if(b)return this.yieldAllStep_("return"in b?b["return"]:function(a){return{value:a,done:!0}},a,this.context_.return);this.context_.return(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.throw_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_["throw"],a,this.context_.next_);this.context_.throw_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.yieldAllStep_=function(a,b,d){try{var e=a.call(this.context_.yieldAllIterator_,b);$jscomp.generator.ensureIteratorResultIsObject_(e);if(!e.done)return this.context_.stop_(),e;var c=e.value}catch(f){return this.context_.yieldAllIterator_=null,this.context_.throw_(f),this.nextStep_()}this.context_.yieldAllIterator_=null;d.call(this.context_,c);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.nextStep_=function(){for(;this.context_.nextAddress;)try{var a=this.program_(this.context_);if(a)return this.context_.stop_(),{value:a.value,done:!1}}catch(b){this.context_.yieldResult=void 0,this.context_.throw_(b)}this.context_.stop_();if(this.context_.abruptCompletion_){a=this.context_.abruptCompletion_;this.context_.abruptCompletion_=null;if(a.isException)throw a.exception;return{value:a.return,done:!0}}return{value:void 0,done:!0}};
$jscomp.generator.Generator_=function(a){this.next=function(b){return a.next_(b)};this.throw=function(b){return a.throw_(b)};this.return=function(b){return a.return_(b)};$jscomp.initSymbolIterator();this[Symbol.iterator]=function(){return this}};$jscomp.generator.createGenerator=function(a,b){b=new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(b));$jscomp.setPrototypeOf&&$jscomp.setPrototypeOf(b,a.prototype);return b};
$jscomp.asyncExecutePromiseGenerator=function(a){function b(b){return a.next(b)}function d(b){return a.throw(b)}return new Promise(function(e,c){function f(a){a.done?e(a.value):Promise.resolve(a.value).then(b,d).then(f,c)}f(a.next())})};$jscomp.asyncExecutePromiseGeneratorFunction=function(a){return $jscomp.asyncExecutePromiseGenerator(a())};$jscomp.asyncExecutePromiseGeneratorProgram=function(a){return $jscomp.asyncExecutePromiseGenerator(new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(a)))};
$jscomp.iteratorFromArray=function(a,b){$jscomp.initSymbolIterator();a instanceof String&&(a+="");var d=0,e={next:function(){if(d<a.length){var c=d++;return{value:b(c,a[c]),done:!1}}e.next=function(){return{done:!0,value:void 0}};return e.next()}};e[Symbol.iterator]=function(){return e};return e};$jscomp.polyfill("Array.prototype.keys",function(a){return a?a:function(){return $jscomp.iteratorFromArray(this,function(a){return a})}},"es6","es3");
$jscomp.checkStringArgs=function(a,b,d){if(null==a)throw new TypeError("The 'this' value for String.prototype."+d+" must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype."+d+" must not be a regular expression");return a+""};
$jscomp.polyfill("String.prototype.startsWith",function(a){return a?a:function(a,d){var b=$jscomp.checkStringArgs(this,a,"startsWith");a+="";var c=b.length,f=a.length;d=Math.max(0,Math.min(d|0,b.length));for(var k=0;k<f&&d<c;)if(b[d++]!=a[k++])return!1;return k>=f}},"es6","es3");
$jscomp.polyfill("String.prototype.endsWith",function(a){return a?a:function(a,d){var b=$jscomp.checkStringArgs(this,a,"endsWith");a+="";void 0===d&&(d=b.length);d=Math.max(0,Math.min(d|0,b.length));for(var c=a.length;0<c&&0<d;)if(b[--d]!=a[--c])return!1;return 0>=c}},"es6","es3");var Dynamsoft="undefined"!=typeof Dynamsoft?Dynamsoft:("undefined"!=typeof Dynamsoft?window.Dynamsoft:void 0)||{license:"",workerPathPdfR:"",workerPathPdfW:"",workerPathImgcore:""};Dynamsoft.error=Dynamsoft.error||{};
Dynamsoft.error.code=Dynamsoft.error.code||{};Dynamsoft.error.code.wasmBase=-4E3;Dynamsoft.error.code.wasmException=Dynamsoft.error.code.wasmBase-1;Dynamsoft.error.code.wasmNoModule=Dynamsoft.error.code.wasmBase-1;Dynamsoft.error.code.wasmJsBase=-4100;Dynamsoft.error.code.wasmJsObjectNotInit=Dynamsoft.error.code.wasmJsBase-1;Dynamsoft.error.code.wasmJsObjectTerminated=Dynamsoft.error.code.wasmJsBase-1;Dynamsoft.error.code.wasmJsObjectInitFailed=Dynamsoft.error.code.wasmJsBase-1;
Dynamsoft.error.code.wasmJsNotLoaded=Dynamsoft.error.code.wasmJsBase-1;Dynamsoft.error.code.wasmJsInvalidJson=Dynamsoft.error.code.wasmJsBase-1;Dynamsoft.error.code.wasmJsWorkerRunException=Dynamsoft.error.code.wasmJsBase-1;Dynamsoft.error.code.wasmJsWorkerRunFailed=Dynamsoft.error.code.wasmJsBase-1;Dynamsoft.error.code.wasmJsReadFileFailed=Dynamsoft.error.code.wasmJsBase-1;Dynamsoft.error.code.wasmJsCoreTaskException=Dynamsoft.error.code.wasmJsBase-1;
Dynamsoft.error.code.wasmJsProcTaskException=Dynamsoft.error.code.wasmJsBase-1;Dynamsoft.error.code.wasmJsSavePdfFailed=Dynamsoft.error.code.wasmJsBase-1;Dynamsoft.error.code.wasmJsSaveTiffFailed=Dynamsoft.error.code.wasmJsBase-1;
Dynamsoft.conststring={version:"1.7.1",logInfo:"logInfo",logDebug:"logDebug",logAll:"logAll",initPending:"pending",initReady:"ready",initFailed:"failed",imgIO:"imgIO",core:"imgCore",imgProc:"imgProc",pdfR:"pdfReader",pdfW:"pdfWriter",crypto:"crypto",binaryBlobType:"application/octet-stream",wasmExtension:".wasm"};
Dynamsoft.WasmEnv={moduleNames:[Dynamsoft.conststring.imgIO,Dynamsoft.conststring.crypto,Dynamsoft.conststring.core,Dynamsoft.conststring.imgProc,Dynamsoft.conststring.pdfR,Dynamsoft.conststring.pdfW],imgIO:{name:Dynamsoft.conststring.imgIO,ver:Dynamsoft.conststring.version,status:"",prefixName:"dynamsoft.imageio-",wasmModule:null},imgCore:{name:Dynamsoft.conststring.core,autoLoad:!0,ver:Dynamsoft.conststring.version,status:"",prefixName:"dynamsoft.imagecore-",wasmModule:null},imgProc:{name:Dynamsoft.conststring.imgProc,
autoLoad:!0,ver:Dynamsoft.conststring.version,status:"",prefixName:"dynamsoft.imageProc-",wasmModule:null},pdfReader:{name:Dynamsoft.conststring.pdfR,autoLoad:!0,ver:Dynamsoft.conststring.version,status:"",prefixName:"dynamsoft.pdfReader-",wasmModule:null},pdfWriter:{name:Dynamsoft.conststring.pdfW,autoLoad:!0,ver:Dynamsoft.conststring.version,status:"",prefixName:"dynamsoft.pdfWriter-",wasmModule:null},crypto:{name:Dynamsoft.conststring.crypto,autoLoad:!0,ver:Dynamsoft.conststring.version,status:"",
prefixName:"dynamsoft.crypto-",wasmModule:null}};Dynamsoft.Enum_ImageType={IT_DIB:-1,IT_RGBA:-2,IT_BMP:0,IT_JPG:1,IT_PNG:3,IT_ALL:5};Dynamsoft.Enum_ReturnType={RT_AUTO:-1,RT_BINARY:1,RT_BASE64:2};Dynamsoft.Enum_ErrorMessage={PARAMETER_TYPE_ERROR:"Parameter Type not Supported: ",TIMEOUT:"Timeout no Response: ",FILE_STREAM_ERROR:"File Stream Error: ",WASM_EXCEPTION_ERROR:"An WASM exception occurred."};var Dynmasoft=Dynamsoft||{};Dynamsoft.Lib=Dynamsoft.Lib||{};Dynamsoft.Lib.env=Dynamsoft.Lib.env||{};
Dynamsoft.b64ToUint6=function(a){return 64<a&&91>a?a-65:96<a&&123>a?a-71:47<a&&58>a?a+4:43===a?62:47===a?63:0};Dynamsoft.base64DecToArr=function(a,b){a=a.replace(/[^A-Za-z0-9\+\/]/g,"");var d=a.length;b=b?Math.ceil((3*d+1>>>2)/b)*b:3*d+1>>>2;for(var e=new Uint8Array(b),c,f=0,k=0,g=0;g<d;g++)if(c=g&3,f|=Dynamsoft.b64ToUint6(a.charCodeAt(g))<<18-6*c,3===c||1===d-g){for(c=0;3>c&&k<b;c++,k++)e[k]=f>>>(16>>>c&24)&255;f=0}return e};
Dynamsoft.isWasmSupport=function(){try{if("object"===typeof WebAssembly&&"function"===typeof WebAssembly.instantiate){var a=new WebAssembly.Module(Uint8Array.of(0,97,115,109,1,0,0,0));if(a instanceof WebAssembly.Module)return new WebAssembly.Instance(a)instanceof WebAssembly.Instance}}catch(b){}return!1};Dynamsoft.random=function(){return(Date.now()%10086).toString(36).slice(2)+Math.random().toString(36).slice(2)};
Dynamsoft.readFile=function(a){return new Promise(function(b,d){var e=Object.prototype.toString.call(a);if("[object String]"===e)0===a.indexOf("blob:")||0<a.indexOf(".jpg")||0<a.indexOf(".jpeg")||0<a.indexOf(".png")||0<a.indexOf(".bmp")||0<a.indexOf(".dib")||0<a.indexOf(".pdf")||0<a.indexOf(".tiff")||0<a.indexOf(".tif")?fetch(a,{mode:"cors"}).then(function(a){return a.arrayBuffer()}).then(function(a){return b(a)}).catch(function(a){return Promise.reject(a)}):d("Error url: Can not read the file URL");
else if("[object Blob]"===e){var c=new FileReader;c.readAsArrayBuffer(a);c.onload=function(){var a=c.result;c=null;b(a)}}else"[object FileList]"===e||"[object File]"===e?(d=a[0]?a[0]:a,c=new FileReader,c.readAsArrayBuffer(d),c.onload=function(){var a=c.result;c=null;b(a)}):"[object ArrayBuffer]"===e||"[object Uint8ClampedArray]"===e?b(a):d("Not support source type: "+e)})};
Dynamsoft.base64Decode=function(a){function b(a){var c=[],b=a.length,d;for(d=0;d<b;d++){var e=a.charCodeAt(d);if(0==(e>>7&255))c.push(a.charAt(d));else if(6==(e>>5&255)){var h=a.charCodeAt(++d);e=(e&31)<<6;h&=63;e|=h;c.push(String.fromCharCode(e))}else if(14==(e>>4&255)){h=a.charCodeAt(++d);var l=a.charCodeAt(++d);e=e<<4|h>>2&15;h=(h&3)<<6|l&63;e=(e&255)<<8|h;c.push(String.fromCharCode(e))}}return c.join("")}var d=[-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,62,-1,-1,-1,63,52,53,54,55,56,57,58,59,60,61,-1,-1,-1,-1,-1,-1,-1,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,-1,-1,-1,-1,-1,-1,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,-1,-1,-1,-1,-1];return function(a){for(var c=[],f=0,e=a.length,g,h;f<e;){do g=d[a.charCodeAt(f++)&255];while(f<e&&-1==g);if(-1==g)break;do h=d[a.charCodeAt(f++)&255];while(f<e&&-1==h);if(-1==h)break;c.push(String.fromCharCode(g<<
2|(h&48)>>4));do{g=a.charCodeAt(f++)&255;if(61==g)return b(c.join(""));g=d[g]}while(f<e&&-1==g);if(-1==g)break;c.push(String.fromCharCode((h&15)<<4|(g&60)>>2));do{h=a.charCodeAt(f++)&255;if(61==h)return b(c.join(""));h=d[h]}while(f<e&&-1==h);if(-1==h)break;c.push(String.fromCharCode((g&3)<<6|h))}return b(c.join(""))}(a)};Dynamsoft.WasmEnv=Dynamsoft.WasmEnv||{};Dynamsoft.WasmEnv.lastInstanceId=0;Dynamsoft.WasmEnv.worker={maxWorkers:1,liveTime:60};
Dynamsoft.WasmEnv.resourceDir=Dynamsoft.DWT.ResourcesPath+"/src/";Dynamsoft.WasmEnv.wasmJS="dynamsoft.imageio_wasm-"+Dynamsoft.conststring.version+".js";Dynamsoft.WasmEnv.logLevel=Dynamsoft.DWT.Debug?Dynamsoft.conststring.logDebug:0;Dynamsoft.WasmEnv.logFunc=null;Dynamsoft.WasmEnv.productKey="";Dynamsoft.WasmEnv.licMode=0;Dynamsoft.WasmEnv.uuid="";Dynamsoft.WasmEnv.fetchOptions={mode:"cors",credentials:"same-origin"};Dynamsoft.WasmEnv.maxHeapSize=200;
Dynamsoft.WasmEnv.log=function(a,b){var d=Dynamsoft.WasmEnv;d.logLevel===b&&("function"===typeof d.logFunc?d.logFunc(a):console.log(a))};Dynamsoft.WasmEnv.clear=function(){for(var a=$jscomp.makeIterator(Dynamsoft.WasmEnv.moduleNames),b=a.next();!b.done;b=a.next())b=b.value,Dynamsoft.WasmEnv[b].status="",delete Dynamsoft.WasmEnv[b].error};Dynamsoft.WasmEnv.setLoglevel=function(a,b){Dynamsoft.WasmEnv.logLevel=1===a?Dynamsoft.conststring.logDebug:0;Dynamsoft.WasmEnv.logFunc=b};
Dynamsoft.WorkerHandler=function(a,b){function d(a){e.terminated=!0;e.terminating&&e.terminationHandler&&e.terminationHandler(e);e.terminating=!1;e.cancelAllTasks()}var e=this;this.options=b||{};this.script=a;this.worker=function(a){if("function"!==typeof Worker&&("object"!==typeof Worker||"function"!==typeof Worker.prototype.constructor))throw Error("Web Workers not supported");a=new Worker(a);a.on=function(a,c){this.addEventListener(a,function(a){c(a.data)})};a.send=function(a){if(void 0!=a&&void 0!=
a.params&&void 0!=a.params.input){var c=Object.prototype.toString.call(a.params.input);if("[object Array]"===Object.prototype.toString.call(a.params.input)){if(c=Object.prototype.toString.call(a.params.input[0]),"[object ArrayBuffer]"===c||"[object Uint8ClampedArray]"===c){this.postMessage(a,[void 0!=a.params.input[0].buffer?a.params.input[0].buffer:a.params.input[0]]);return}}else if("[object ArrayBuffer]"===c||"[object Uint8ClampedArray]"===c){this.postMessage(a,[void 0!=a.params.input.buffer?a.params.input.buffer:
a.params.input]);return}}this.postMessage(a)};return a}(this.script);this.requestQueue=[];this.terminated=this.terminating=!1;e.tasks=Object.create(null);this.objectToError=function(a){for(var c=Error(""),b=Object.keys(a),d=0;d<b.length;d++)c[b[d]]=a[b[d]];return c};this.dispatchQueuedRequests=function(){e.requestQueue.forEach(e.worker.send.bind(e.worker));e.requestQueue=[]};this.dispatchRequest=function(a){a.forEach(e.worker.send.bind(e.worker))};this.worker.on("message",function(a){"function"===
typeof e.options.log&&e.options.log(a.log?a.log:a,e.context);if("string"===typeof a&&"ready"===a)e.worker.ready=!0,e.dispatchQueuedRequests();else if(!a.log){if("object"===typeof a){var c=a.result;"object"===typeof c?(void 0!=c.errorCode&&(c.code=c.errorCode,delete c.errorCode),void 0!=c.errorMessage&&(c.message=c.errorMessage,delete c.errorMessage)):"string"===typeof c&&(c=c.replace('"errorCode"','"code"'),c=c.replace("'errorCode'","'code'"),c=c.replace('"errorMessage"','"message"'),c=c.replace("'errorMessage'",
"'message'"),a.result=c);void 0!=a.memSize&&(e.memSize=a.memSize)}c=a.id;var b=e.tasks[c];void 0!==b?(delete e.tasks[c],!0===e.terminating&&e.terminate(),"loadWasm"===a.func&&void 0!=a.result&&(e.worker.wasmReady=!0,e.dispatchQueuedRequests()),a.error?b.resolver.reject(e.objectToError(a.error)):a.result&&b.resolver.resolve(a.result)):"loadWasm"===a.func&&void 0!=a.result&&Dynamsoft.WasmEnv._handleWasmLoad(a.result,e)}});this.worker.on("error",d);this.worker.on("exit",function(a,b){a="Worker terminated Unexpectedly\n exitCode: `"+
(a+"`\n signalCode: `")+(b+"`\n script: `")+(e.script+"`\n");d(Error(a))});this.terminated=this.terminating=!1;this.terminationHandler=null;this.lastTaskId=0};
Dynamsoft.WorkerHandler.prototype.exec=function(a,b,d){d||(d={},d.promise=new Promise(function(a,b){d.resolve=a;d.reject=b}));var e=++this.lastTaskId;this.tasks[e]={id:e,resolver:d};b={id:e,func:a,params:b};this.terminated?d.reject(Error("Worker is terminated")):this.terminating?d.reject(Error("Worker is terminating")):this.worker.wasmReady||this.worker.ready&&"loadWasm"===a?this.worker.send(b):this.requestQueue.push(b);return d.promise};
Dynamsoft.WorkerHandler.prototype.busy=function(){return 0<this.howManyTasks()};Dynamsoft.WorkerHandler.prototype.howManyTasks=function(){return Object.keys(this.tasks).length};Dynamsoft.WorkerHandler.prototype.cancelAllTasks=function(a){for(var b in this.tasks)void 0!==this.tasks[b]&&this.tasks[b].resolver.reject(Error(a));this.tasks=Object.create(null)};Dynamsoft.WorkerHandler.prototype.alive=function(){return this.terminating||this.terminated?!1:!0};
Dynamsoft.WorkerHandler.prototype.terminate=function(a,b){a&&this.cancelAllTasks("Worker has been terminated");"function"===typeof b&&(this.terminationHandler=b);if(this.busy())this.terminating=!0;else{if(this.worker){if("function"===typeof this.worker.terminate)this.worker.terminate();else throw Error("Failed to terminate worker");this.worker=null}this.terminating=!1;this.terminated=!0;this.terminationHandler&&this.terminationHandler(this)}};
Dynamsoft.WorkerHandler.prototype.setLogCallback=function(a,b){this.options.log=a;this.context=b};
Dynamsoft.WorkerPool=function(a,b){var d=this;this.workers=[];this.options=a;this.maxWorkers=1;this.script=this.options.resourceDir+this.options.wasmJS;this.ready=!1;this.pdfReaderInstance=null;this.terminated=!1;this.wasmLoaderPromise=Object.create(null);this._getMaxWorkers=function(){var a=2;"hardwareConcurrency"in self.navigator&&(a=self.navigator.hardwareConcurrency);return Math.max(Math.min(d.options.worker.maxWorkers,Math.max(d.options.worker.maxWorkers,a/2)),1)};this._logAll=function(a){Dynamsoft.WasmEnv.log(a,
Dynamsoft.conststring.logAll)};this._log=function(a,c){Dynamsoft.WasmEnv.log(a,Dynamsoft.conststring.logDebug)};this._createWorker=function(){d.ready&&(d.maxWorkers=d._getMaxWorkers());var a=d.workers;if(a.length<d.maxWorkers){var c=new Dynamsoft.WorkerHandler(d.script);a.push(c);c.id=a.length;c.module={};c.module.modulesInfo=[];c.instances=Object.create(null);c.setLogCallback(this._log,d);d._logAll(a);d.log("get new worker "+c.id+" succeed!");return c}return null};this._getContainedModuleWorkers=
function(a){d._removeTerminatedWorker();var c=d.workers;d._logAll(c);for(var b=[],e=0;e<c.length;e++){var g=c[e];!g.module.modulesInfo[a.name]||g.busy()&&c.length<d.maxWorkers||b.push(g)}d._logAll("get workers for module "+a.name);d._logAll(b);return b};this._getIdleWorker=function(){d._removeTerminatedWorker();for(var a=d.workers,c=0;c<a.length;c++){var b=a[c];if(!1===b.busy())return b}return d._createWorker()};this._busy=function(){d._removeTerminatedWorker();for(var a=d.workers,c=0;c<a.length;c++)if(a[c].busy())return!0;
return!1};this._removeTerminatedWorker=function(){d.workers=d.workers.filter(function(a){return!a.terminated})};this._getWorkerByIntanceId=function(a,c){d._logAll("_getWorkerByIntanceId");d._logAll(a);for(var b=9007199254740991,e=null,g=0;g<a.length;g++){var h=a[g];if(void 0!=h.instances[c]){e=h;break}else{var l=h.howManyTasks();l<b&&(e=h,b=l)}}if(e)return e.instances[c]="",d._logAll(a),d.log("get worker "+c+" in "+e.id+" succeed!"),e;d._logAll("_getWorkerByIntanceId: no suitable worker");return null};
this._initWorkerInner=function(a,c,b){try{c.params&&(c.params.resourceDir=this.resourceDir,c.params.fetchOptions=Dynamsoft.WasmEnv.fetchOptions);for(var e=$jscomp.makeIterator(c.params.module.modulesInfo),f=e.next();!f.done;f=e.next())Dynamsoft.WasmEnv[f.value.name].status=Dynamsoft.conststring.initPending;a.exec(c.func,c.params).then(function(c){void 0===c.code||c.modules?Dynamsoft.WasmEnv._handleWasmLoad(c,a):d.log(c);b()}).catch(function(a){d.log(a);b()})}catch(h){d.log(h),b()}};this._removeInstanceInWorker=
function(a,c){var b=d.workers;d._logAll("removeInstanceInWorker");d._logAll(b);for(var e=0;e<b.length;e++){var g=b[e];if(g===a){void 0!=g.instances[c]?(delete g.instances[c],d._logAll(b),d.log("removeInstanceInWorker "+c+" in "+g.id+" succeed!")):d.log("not found instance "+c);break}}};this._hasInstanceInWorker=function(){for(var a=d.workers,c=0;c<a.length;c++)if(0!=Object.keys(a[c].instances).length)return!0;return null!=d.pdfReaderInstance};this._getWorker=function(a,c){if(Dynamsoft.WasmEnv[a.name].status==
Dynamsoft.conststring.initPending)return null;var b=d._getContainedModuleWorkers(a);if(0!=b.length)return d._getWorkerByIntanceId(b,c);if(c=d._getIdleWorker()){if(c.module.modulesInfo[a.name])return c;a={id:0,func:"loadWasm",params:{priority:0,key:d.options.productKey,module:{modulesInfo:[]}}};b=$jscomp.makeIterator(Dynamsoft.WasmEnv.moduleNames);for(var e=b.next();!e.done;e=b.next())e=e.value,a.params.module.modulesInfo.push({name:e,ver:Dynamsoft.WasmEnv[e].ver,wasmModule:Dynamsoft.WasmEnv[e].wasmModule});
d._initWorkerInner(c,a,function(){})}return null};this._init=function(a){var c=d._createWorker();c&&(c.setLogCallback(function(a,c){c.log(a)},d),a.params.callback=null,d._initWorkerInner(c,a,function(a){d.maxWorkers=d._getMaxWorkers();d.ready=!0}))};this._initAsync=function(a){var c=this,b,d;return $jscomp.asyncExecutePromiseGeneratorProgram(function(e){if(1==e.nextAddress)return d=b=c,e.yield(fetch(b.script).then(function(a){return a.blob()}).then(function(a){return URL.createObjectURL(a)}),2);d.script=
e.yieldResult;b._init(a);e.jumpToEnd()})};this._getPath=function(){this.script.startsWith("http://")||this.script.startsWith("https://")?this.resourceDir=this.options.resourceDir:this.options.resourceDir.startsWith("/")?null!=location.origin&&(this.resourceDir=location.origin+this.options.resourceDir):null!=location.href&&(this.resourceDir=location.href.substring(0,location.href.lastIndexOf("/")+1)+this.options.resourceDir);this.resourceDir.endsWith("/")||(this.resourceDir+="/")};this._getPath();
if(b&&0<b.params.module.modulesInfo.length){a=!1;if(this.script.startsWith("http://")||this.script.startsWith("https://"))this.script.startsWith(location.origin)||(a=!0);a?this._initAsync(b):this._init(b)}else d.maxWorkers=d._getMaxWorkers(),d.ready=!0};
Dynamsoft.WorkerPool.prototype.getWorker=function(a,b){if(!this.ready)return null;var d=a.name===Dynamsoft.WasmEnv.pdfReader.name;if(d&&this.pdfReaderInstance)return null;if((a=this._getWorker(a,b))&&d){if(this.pdfReaderInstance)return this._removeInstanceInWorker(a,b),null;this.pdfReaderInstance=b}return a};
Dynamsoft.WorkerPool.prototype.removeInstanceInWorker=function(a,b,d,e){this._removeInstanceInWorker(b,d);a.name===Dynamsoft.WasmEnv.pdfReader.name&&this.pdfReaderInstance&&(this.pdfReaderInstance=null);e&&b&&void 0!=b.memSize&&(a=1048576*Dynamsoft.WasmEnv.maxHeapSize,Dynamsoft.WasmEnv.log("current memSize="+b.memSize+", max="+a,Dynamsoft.conststring.logDebug),b.memSize>a&&0!=a&&!this._hasInstanceInWorker()&&(Dynamsoft.WasmEnv.log("reload wasm auto",Dynamsoft.conststring.logDebug),Dynamsoft.WasmEnv.load()))};
Dynamsoft.WorkerPool.prototype.log=function(a){Dynamsoft.WasmEnv.log(a,Dynamsoft.conststring.logDebug)};Dynamsoft.WorkerPool.prototype.terminate=function(a){this.terminated=!0;var b=[],d=this.workers.slice();this.workers=[];d.forEach(function(d){var c={};c.promise=new Promise(function(a,b){c.resolve=a;c.reject=b});b.push(c.promise);d.terminate(a,function(a){c.resolve(a)})});return Promise.all(b)};
Dynamsoft.WorkerPool.prototype.getMemoryUsed=function(){for(var a=this.workers,b=[],d=0;d<a.length;d++){var e=a[d];e&&void 0!=e.memSize&&(b[d]=e.memSize)}return b};
Dynamsoft.WasmEnv.load=function(a,b,d){Dynamsoft.WasmEnv.unload();Dynamsoft.WasmEnv.productKey=void 0!=a?a:Dynamsoft.WasmEnv.productKey;Dynamsoft.WasmEnv.licMode=void 0!=b?b?1:0:Dynamsoft.WasmEnv.licMode;Dynamsoft.WasmEnv.uuid=void 0!=d?d:Dynamsoft.WasmEnv.uuid;Dynamsoft.WasmEnv.licensePromise={};Dynamsoft.WasmEnv.licensePromise.promise=new Promise(function(a,b){Dynamsoft.WasmEnv.licensePromise.resolve=a;Dynamsoft.WasmEnv.licensePromise.reject=b});var e=Dynamsoft.WasmEnv;e.clear();a={id:0,func:"loadWasm",
params:{priority:0,key:a,licMode:Dynamsoft.WasmEnv.licMode,uuid:Dynamsoft.WasmEnv.uuid,module:{modulesInfo:[]},callback:function(a){e.logLevel===Dynamsoft.conststring.logDebug&&("function"===typeof e.logFunc?e.logFunc(a):console.log(a))}}};a.params.module.modulesInfo.push({name:e.imgIO.name,ver:e.imgIO.ver,wasmModule:e.imgIO.wasmModule});1===Dynamsoft.WasmEnv.licMode&&a.params.module.modulesInfo.push({name:e.crypto.name,ver:e.crypto.ver,wasmModule:e.crypto.wasmModule});(e.imgCore.autoLoad||e.imgCore.wasmModule)&&
a.params.module.modulesInfo.push({name:e.imgCore.name,ver:e.imgCore.ver,wasmModule:e.imgCore.wasmModule});(e.imgProc.autoLoad||e.imgProc.wasmModule)&&a.params.module.modulesInfo.push({name:e.imgProc.name,ver:e.imgProc.ver,wasmModule:e.imgProc.wasmModule});(e.pdfReader.autoLoad||e.pdfReader.wasmModule)&&a.params.module.modulesInfo.push({name:e.pdfReader.name,ver:e.pdfReader.ver,wasmModule:e.pdfReader.wasmModule});(e.pdfWriter.autoLoad||e.pdfWriter.wasmModule)&&a.params.module.modulesInfo.push({name:e.pdfWriter.name,
ver:e.pdfWriter.ver,wasmModule:e.pdfWriter.wasmModule});Dynamsoft.WorkerPool.Instance=null;Dynamsoft.WorkerPool.Instance=new Dynamsoft.WorkerPool(e,a)};Dynamsoft.WasmEnv.unload=function(){var a=Dynamsoft.WorkerPool.Instance;return void 0!=a?a.terminate(!0):Promise.resolve()};Dynamsoft.WasmEnv.getWorkerPool=function(){var a=Dynamsoft.WorkerPool.Instance;return a&&a.terminated?null:a};Dynamsoft.WasmEnv.busy=function(){var a=Dynamsoft.WorkerPool.Instance;return a?a._busy():!1};
Dynamsoft.WasmEnv._handleWasmLoad=function(a,b){Dynamsoft.WasmEnv.log("handleWasmLoad:",Dynamsoft.conststring.logDebug);Dynamsoft.WasmEnv.log(a,Dynamsoft.conststring.logDebug);if("object"!=typeof a||void 0==a.modules)"object"===typeof a&&Dynamsoft.WasmEnv.licensePromise.reject({code:a.code,message:a.message});else{for(var d=$jscomp.makeIterator(a.modules),e=d.next();!e.done;e=d.next())e=e.value,a.code?(Dynamsoft.WasmEnv[e.name].error={code:a.code,message:a.message},b.module.modulesInfo[e.name]=!1):
(delete Dynamsoft.WasmEnv[e.name].error,Dynamsoft.WasmEnv[e.name].status=Dynamsoft.conststring.initReady,Dynamsoft.WasmEnv[e.name].wasmModule=e.wasmModule,b.module.modulesInfo[e.name]=!0);a.licenseInfo&&(a=a.licenseInfo,"string"===typeof a&&(a=JSON.parse(a)),Dynamsoft.WasmEnv.licensePromise.resolve(a));void 0!=Dynamsoft.WasmEnv.imgIO.error&&Dynamsoft.WasmEnv.licensePromise.reject(Dynamsoft.WasmEnv.imgIO.error)}};
Dynamsoft.ImageIoBase=function(a,b,d,e){var c=this;this.moduleInfo=b;this.name=this.moduleInfo.name;this.outputType=Dynamsoft.Enum_ImageType.IT_JPG;this.inputType=Dynamsoft.Enum_ImageType.IT_ALL;this.tiffFormat=0;this.jpegQuality=80;this.tasksQueue=[];this.worker=null;this.lastTaskId=0;this.logFunc=d;this.context=e;this.instanceId=++Dynamsoft.WasmEnv.lastInstanceId;this.timer=null;this.nv=JSON.parse(JSON.stringify(Dynamsoft.navInfo));this.mb=Dynamsoft.Lib.env.bMobile;this.dm=location.origin;this.initStatus=
"";this.terminated=!1;this.license=a?a:Dynamsoft.license;this.license||(this.license="");this.licMode=Dynamsoft.WasmEnv.licMode;this.uuid=Dynamsoft.WasmEnv.uuid;this._getWorker=function(){c.timer&&clearTimeout(c.timer);if(c.worker&&c.worker.alive())return c.worker;var a=Dynamsoft.WasmEnv.getWorkerPool();if(a){c.worker=a.getWorker(c.moduleInfo,c.instanceId);if(c.worker&&c.worker.alive())0<c.tasksQueue.length&&c._dispatchQueuedTasks();else{if(Dynamsoft.WasmEnv[c.name].error)return c._cancelAllTasks(Dynamsoft.error.code.wasmJsNotLoaded,
Dynamsoft.WasmEnv[c.name].error),c.worker;0<c.tasksQueue.length&&(c.timer=setTimeout(c._getWorker,50))}return c.worker}c._cancelAllTasks(Dynamsoft.error.code.wasmJsNotLoaded,"wasm env not loaded")};this._dispatchQueuedTasks=function(){c._logAll(c.tasksQueue,c);if(c.worker&&c.worker.alive()){if(0<c.tasksQueue.length){var a=c.tasksQueue[0];if(c.initStatus===Dynamsoft.conststring.initReady||"init"===a.func)delete c.tasksQueue[0],c.tasksQueue.splice(0,1),c._exec(a)}}else c.worker&&!c.worker.alive()&&
0<c.tasksQueue.length&&"init"!=c.tasksQueue[0].func?(c.worker=null,c._init()):0<c.tasksQueue.length&&c._getWorker()};this._log=function(a,c){"function"===typeof c.logFunc?c.logFunc(a,c.context):Dynamsoft.WasmEnv.log(a,Dynamsoft.conststring.logDebug)};this._logAll=function(a,c){Dynamsoft.WasmEnv.logLevel===Dynamsoft.conststring.logAll&&this._log(a,c)};this._handleReject=function(a,c,b){var d=c;"object"!=typeof d&&(d={},d.code=b,d.message=c);return this.terminated?a.resolve(d):a.reject(d)};this._handleBasicResult=
function(a,c){delete a.code;delete a.message;return a};this._handleBooleanResult=function(a,c){return!0};this._handleImageData=function(a,c){if("object"===typeof a.imageData)if(void 0!=a.imageCount&&1<a.imageCount)for(c=0;c<a.imageCount;c++)a.imageData[c]=URL.createObjectURL(a.imageData[c]);else a.imageData=URL.createObjectURL(a.imageData);"object"===typeof a.pdfData&&(a.pdfData=URL.createObjectURL(a.pdfData));return a};this._handleResult=function(a,b){a=b.context._getResult(a);void 0===a.code||!a.code&&
"Successful."===a.message?(a=b.handleResult(a,b),c._dispatchQueuedTasks(),b=b.resolve,b(a)):(a={code:a.code,message:a.code===Dynamsoft.error.code.wasmException?Dynamsoft.Enum_ErrorMessage.WASM_EXCEPTION_ERROR:a.message},this.terminated?b.resolve(a):b.reject(a))};this._getResult=function(a){try{return"string"===typeof a?JSON.parse(a):a}catch(k){return a}};this._exec=function(a){var b=c.worker;b.setLogCallback(c._log,c);c._logAll(a,c);try{b.exec(a.func,a.params).then(function(b){c._log(b,c);c._handleResult(c._getResult(b),
a)}).catch(function(b){c._log(b,c);c._dispatchQueuedTasks();var d=b;"object"===typeof b&&(void 0!=b.message?d=b.message:void 0!=b.message&&(d=b.message));b={code:Dynamsoft.error.code.wasmJsWorkerRunFailed,message:d};c.terminated?a.resolve(b):a.reject(b)})}catch(g){c._dispatchQueuedTasks(),c._log(g,c),b={code:Dynamsoft.error.code.wasmJsWorkerRunException,message:g.message,stack:g.stack},c.terminated?a.resolve(b):(b,a.reject(b))}};this._cancelAllTasks=function(a,b){for(var d=0;d<c.tasksQueue.length;d++)if(void 0!==
c.tasksQueue[d]){var e={code:a,message:b};c.terminated?c.tasksQueue[d].resolve(e):c.tasksQueue[d].reject(e)}c.tasksQueue=[]};this._createTask=function(a,b,c){var d={id:++this.lastTaskId};d.promise=new Promise(function(a,b){d.resolve=a;d.reject=b});d.func=a;d.params={moduleName:this.name,insId:this.instanceId,fetchOptions:Dynamsoft.WasmEnv.fetchOptions};d.context=this;d.handleResult="undefined"!==typeof c&&c?c:this._handleBasicResult;d.params.input="undefined"!==typeof b&&b?b:"";d.params.returnType=
"";return d};this._addTask=function(a,b){""===this.initStatus?a.reject({code:Dynamsoft.error.code.wasmJsObjectNotInit,message:this.terminated?"object has been disposed":"object not init"}):this.initStatus===Dynamsoft.conststring.initFailed?a.reject({code:Dynamsoft.error.code.wasmJsObjectInitFailed,message:c.initError}):(b?c.tasksQueue.unshift(a):c.tasksQueue.push(a),c._dispatchQueuedTasks());return a.promise};this._init=function(){var a=this._createTask("init");a.params.key=this.license;a.params.uuid=
this.uuid;a.params.licMode=this.licMode;a.params.val={nv:this.nv,mb:this.mb,dm:this.dm};a.handleResult=function(a,b){b.context.initStatus=Dynamsoft.conststring.initReady;return a};this.initStatus=Dynamsoft.conststring.initPending;this._addTask(a,!0);a.promise.then(function(a){c._log(c.name+" init return: ",c);c._log(a,c)}).catch(function(a){c.initStatus=Dynamsoft.conststring.initFailed;c.initError=a.message;c._log(c.name+" init failed",c);c._log(a,c);c._cancelAllTasks(Dynamsoft.error.code.wasmJsObjectInitFailed,
a.message)})};this._destroy=function(){var a=this._createTask("destroy");this._addTask(a);return a.promise};this._terminate=function(a){var b=this._destroy();this.terminated=!0;var d=Dynamsoft.WasmEnv.getWorkerPool();d&&d.removeInstanceInWorker(c.moduleInfo,c.worker,c.instanceId,a);b.then(function(a){c.worker=null;c._log(c.name+" destroy return: ",c);c._log(a,c)}).catch(function(a){c.worker=null;c._log(c.name+" destroy failed",c);c._log(a,c)});this.initStatus=""};this._readFile=function(a,b){return new Promise(function(d,
e){Dynamsoft.readFile(a).then(function(a){d(a)},function(a){c._handleReject(b,a,Dynamsoft.error.code.wasmJsReadFileFailed)}).catch(function(a){c._handleReject(b,a,Dynamsoft.error.code.wasmJsReadFileFailed)})})};this._init()};Dynamsoft.ImageIoBase.prototype.terminate=function(a){this._terminate(void 0!=a?a:!0)};
Dynamsoft.ImageIoBase.prototype.downloadData=function(a,b,d,e){a=a?a:Date.now()+"";return(new Promise(function(c,f){if(b){if("base64"===d){var k=Dynamsoft.base64DecToArr(b).buffer;k=new Blob([k],{type:"pdf"==e?"application/pdf":"jpg"==e?"image/jpeg":"image/"+e});k=URL.createObjectURL(k)}else"blob"===d?k=b:f(Dynamsoft.Enum_ErrorMessage.FILE_STREAM_ERROR+"Please read/write image or get page before download!");a=a+"."+e;window.navigator.msSaveBlob&&fetch(k).then(function(a){return a.arrayBuffer()}).then(function(b){b=
new Blob([b]);window.navigator.msSaveOrOpenBlob(b,a);c(a)});f=document.createElement("a");f.href=k;f.download=a;f.click();c(a)}else f(Dynamsoft.Enum_ErrorMessage.FILE_STREAM_ERROR+"Please read/write image or get page before download!")})).catch(function(a){return Promise.reject(a)})};
Dynamsoft.Imagecore=function(a,b,d){a=a?a:Dynamsoft.WasmEnv.productKey;Dynamsoft.ImageIoBase.call(this,a,Dynamsoft.WasmEnv.imgCore,b,d);this.saveImageInner=function(a,b,d,k,g,h,l,p,n,m){var c=this;b=void 0!=b?b:this.inputType;d=void 0!=d?d:0;k=void 0!=k?k:0;g=void 0!=g?g:24;h=void 0!=h?h:96;l=void 0!=l?l:96;n=void 0!=n?n:this.jpegQuality;m=void 0!=m?m:Dynamsoft.Enum_ReturnType.RT_AUTO;c=this;var e=c._createTask("SaveImage");c._readFile(a,e).then(function(a){e.params.input=[a,b,d,k,g,h,l,p,n,m==Dynamsoft.Enum_ReturnType.RT_BASE64];
e.params.returnType=m;e.handleResult=c._handleImageData;c._addTask(e)});return e.promise}};Dynamsoft.Imagecore.prototype=Object.create(Dynamsoft.ImageIoBase.prototype);Dynamsoft.Imagecore.prototype.constructor=Dynamsoft.Imagecore;Dynamsoft.Imagecore.prototype.getImageFormat=function(a){var b=this,d=b._createTask("GetImageFormat");b._readFile(a,d).then(function(a){d.params.input=a;b._addTask(d)});return d.promise};
Dynamsoft.Imagecore.prototype.readImageInfo=function(a){var b=this,d=b._createTask("ReadImageInfo");b._readFile(a,d).then(function(a){d.params.input=a;b._addTask(d)});return d.promise};Dynamsoft.Imagecore.prototype.getMD5=function(a){var b=this,d=b._createTask("GetMD5");b._readFile(a,d).then(function(a){d.params.input=a;d.handleResult=function(a,b){return a.MD5};b._addTask(d)});return d.promise};Dynamsoft.Imagecore.prototype.getLicenseInfo=function(){return this._addTask(this._createTask("GetLicenseInfo"))};
Dynamsoft.Imagecore.prototype.getAesResult=function(a){return this._addTask(this._createTask("GetAesResult",[void 0!=a?a:""]))};Dynamsoft.Imagecore.prototype.saveImage=function(a,b,d,e){return this.saveImageInner(a,null,null,null,null,null,null,b,d,e?Dynamsoft.Enum_ReturnType.RT_BINARY:Dynamsoft.Enum_ReturnType.RT_AUTO)};
Dynamsoft.Imagecore.prototype.readImage=function(a,b,d,e){b=void 0!=b?b:this.outputType;d=void 0!=d?d:this.jpegQuality;e=void 0!=e?e:!1;var c=this,f=c._createTask("ReadImage");c._readFile(a,f).then(function(a){f.params.input=[a,b,d,e];f.handleResult=c._handleImageData;c._addTask(f)});return f.promise};Dynamsoft.Imagecore.prototype.openTiff=function(a){var b=this,d=b._createTask("LoadTiff");b._readFile(a,d).then(function(a){d.params.input=a;b._addTask(d)});return d.promise};
Dynamsoft.Imagecore.prototype.readTiff=function(a,b,d){b=void 0!=b?b:this.outputType;d=void 0!=d?d:this.returnImageAsBase64;return this._addTask(this._createTask("ReadTiffPage",[void 0!=a?a:0,b,d],this._handleImageData))};Dynamsoft.Imagecore.prototype.closeTiff=function(){return this._addTask(this._createTask("EndReadTiff",null,this._handleBooleanResult))};Dynamsoft.Imagecore.prototype.createTiff=function(){return this._addTask(this._createTask("NewTiff",null,this._handleBooleanResult))};
Dynamsoft.Imagecore.prototype.appendImage=function(a,b,d,e){b=void 0!=b?b:this.inputType;d=void 0!=d?d:this.tiffFormat;e=void 0!=e?e:this.jpegQuality;var c=this,f=c._createTask("AppendImageToTiff");c._readFile(a,f).then(function(a){f.params.input=[a,b,d,e];f.handleResult=c._handleBooleanResult;c._addTask(f)});return f.promise};Dynamsoft.Imagecore.prototype.addTag=function(a,b,d){return this._addTask(this._createTask("AddTagToNextPage",[a,b,void 0!=d?d:!0],this._handleBooleanResult))};
Dynamsoft.Imagecore.prototype.getTiff=function(a){var b=this._createTask("GetTiffStream");b.handleResult=this._handleImageData;b.params.returnType=a?Dynamsoft.Enum_ReturnType.RT_BINARY:Dynamsoft.Enum_ReturnType.RT_AUTO;return this._addTask(b)};Dynamsoft.Imagecore.prototype.getMemoryUsed=function(){return this._addTask(this._createTask("getMemoryUsed",null,function(a,b){return a.memoryUsed}))};
Dynamsoft.ImageProc=function(a,b,d){a=a?a:Dynamsoft.WasmEnv.productKey;Dynamsoft.ImageIoBase.call(this,a,Dynamsoft.WasmEnv.imgProc,b,d)};Dynamsoft.ImageProc.prototype=Object.create(Dynamsoft.ImageIoBase.prototype);Dynamsoft.ImageProc.prototype.constructor=Dynamsoft.ImageProc;
Dynamsoft.ImageProc.prototype.initImage=function(a,b,d,e){b=void 0!=b?b:!1;d=void 0!=d?d:0;e=void 0!=e?e:0;var c=this,f=c._createTask("InitImageObject");f.handleResult=this._handleBooleanResult;f.params.input=[a,d,e];b?(f.params.input.push(Dynamsoft.Enum_ImageType.IT_RGBA),c._addTask(f)):c._readFile(a,f).then(function(a){f.params.input[0]=a;f.params.input.push(Dynamsoft.Enum_ImageType.IT_ALL);c._addTask(f)});return f.promise};
Dynamsoft.ImageProc.prototype.rotate=function(a,b,d,e){return this._addTask(this._createTask("RotateEx",[a,void 0!=d?d:!1,void 0!=e?e:3,void 0!=b?b:"FFFFFF"],this._handleBooleanResult))};Dynamsoft.ImageProc.prototype.flip=function(a){a=void 0!=a?a:1;var b=this._createTask("");b.handleResult=this._handleBooleanResult;1===a?b.func="Flip":-1===a&&(b.func="Mirror");this._addTask(b);return b.promise};
Dynamsoft.ImageProc.prototype.erase=function(a,b,d,e,c){c=void 0!=c?c:"FFFFFF";var f=this._createTask("Erase");f.handleResult=this._handleBooleanResult;f.params.input=[a,b,d,e,c];this._addTask(f);return f.promise};Dynamsoft.ImageProc.prototype.crop=function(a,b,d,e){return this._addTask(this._createTask("Crop",[a,b,d,e],this._handleBooleanResult))};Dynamsoft.ImageProc.prototype.resize=function(a,b,d){return this._addTask(this._createTask("ChangeImageSize",[a,b,void 0!=d?d:5],this._handleBooleanResult))};
Dynamsoft.ImageProc.prototype.toGrayscale=function(a,b){return this._addTask(this._createTask("ConvertToGrayScale","",this._handleBooleanResult))};Dynamsoft.ImageProc.prototype.toBinary=function(a,b,d){return this._addTask(this._createTask("ConvertToBWScale","",this._handleBooleanResult))};Dynamsoft.ImageProc.prototype.invert=function(){return this._addTask(this._createTask("Invert",null,this._handleBooleanResult))};
Dynamsoft.ImageProc.prototype.setImageWidth=function(a,b){return this._addTask(this._createTask("SetImageWidth",[a,void 0!=b?b:"FFFFFF"],this._handleBooleanResult))};Dynamsoft.ImageProc.prototype.setImageHeight=function(a,b){return this._addTask(this._createTask("SetImageHeight",[a,void 0!=b?b:"FFFFFF"],this._handleBooleanResult))};Dynamsoft.ImageProc.prototype.setDPI=function(a,b,d,e,c,f){return this._addTask(this._createTask("SetDPI",[a,b,d,e,void 0!=c?c:!1,f],this._handleBooleanResult))};
Dynamsoft.ImageProc.prototype.getImage=function(a,b,d,e,c,f){a=void 0!=a?a:this.jpegQuality;return this._addTask(this._createTask("GetCurrentImage",[void 0!=d&&d?Dynamsoft.Enum_ImageType.IT_JPG:Dynamsoft.Enum_ImageType.IT_ALL,void 0!=e?e:24,void 0!=c?c:96,void 0!=f?f:96,!1,a,void 0!=b?b:!0],this._handleImageData))};Dynamsoft.ImageProc.prototype.getSkewAngle=function(a){return this._addTask(this._createTask("GetSkewAngle",[void 0!=a?a:""],function(a,d){return a.skewAngle}))};
Dynamsoft.ImageProc.prototype.freeReservedData=function(){return this._addTask(this._createTask("FreeReservedData",null,this._handleBooleanResult))};Dynamsoft.ImageProc.prototype.detectDocument=function(a){return this._addTask(this._createTask("DocumentDetect",[void 0!=a?a:2]))};Dynamsoft.ImageProc.prototype.perspective=function(a,b,d,e,c,f,k,g){return this._addTask(this._createTask("Perspective",[a,b,d,e,c,f,k,g],this._handleBooleanResult))};Dynamsoft.ImageProcWrapper={};
Dynamsoft.ImageProcWrapper.resize=function(a,b,d,e,c){var f=new Dynamsoft.ImageProc(Dynamsoft.WasmEnv.productKey);return f.initImage(a).then(function(){var a=void 0==c?5:c;var g=b>d?b/e:d/e;return f.resize(b/g,d/g,a)}).then(function(){return f.getImage()}).then(function(a){f.terminate();return a},function(a){f.terminate();return a})};
Dynamsoft.PdfReader=function(a,b,d){a=a?a:Dynamsoft.WasmEnv.productKey;Dynamsoft.ImageIoBase.call(this,a,Dynamsoft.WasmEnv.pdfReader,b,d);this.resolution=200;this.readMode=3;this.outputType=Dynamsoft.Enum_ImageType.IT_ALL};Dynamsoft.PdfReader.prototype=Object.create(Dynamsoft.ImageIoBase.prototype);Dynamsoft.PdfReader.prototype.constructor=Dynamsoft.PdfReader;
Dynamsoft.PdfReader.prototype.open=function(a,b){b=void 0!=b?b:"";var d=this,e=d._createTask("LoadPdf");d._readFile(a,e).then(function(a){e.params.input=[a,b];e.handleResult=function(a,b){var c=Dynamsoft.base64Decode(a.infoBase64);try{try{c.replace(/\\/gi,"\\\\");var d=JSON.parse(c)}catch(l){d=c}return{PdfCount:a.pageCount,PdfInfo:d,isTextBased:a.isTextBased}}catch(l){b.reject({code:Dynamsoft.error.code.wasmJsInvalidJson,message:l.message,stack:l.stack})}};d._addTask(e)});return e.promise};
Dynamsoft.PdfReader.prototype.readPage=function(a,b,d,e,c,f){b=void 0!=b?b:this.resolution;d=void 0!=d?d:this.readMode;e=void 0!=e?e:this.outputType;f=void 0!=f?f:this.returnImageAsBase64;return this._addTask(this._createTask("ReadPdfPage",[void 0!=a?a:0,b,d,e,void 0!=c?c:!1,f],this._handleImageData))};Dynamsoft.PdfReader.prototype.close=function(){return this._addTask(this._createTask("UnloadPdf",null,this._handleBooleanResult))};
Dynamsoft.PdfWriter=function(a,b,d){a=a?a:Dynamsoft.WasmEnv.productKey;Dynamsoft.ImageIoBase.call(this,a,Dynamsoft.WasmEnv.pdfWriter,b,d);this._setPdfSettings=function(a){var b={};if(void 0!=a&&"object"===typeof a)for(var d in a)b[d]=a[d];return b}};Dynamsoft.PdfWriter.prototype=Object.create(Dynamsoft.ImageIoBase.prototype);Dynamsoft.PdfWriter.prototype.constructor=Dynamsoft.PdfWriter;
Dynamsoft.PdfWriter.prototype.initPdfSetting=function(a){var b=this._createTask("InitPdfWriter");b.params.input=JSON.stringify(this._setPdfSettings(a));b.handleResult=this._handleBooleanResult;return this._addTask(b)};Dynamsoft.PdfWriter.prototype.appendPage=function(a){var b=this,d=b._createTask("AddPageFromImageFileStream");b._readFile(a,d).then(function(a){d.params.input=a;d.handleResult=b._handleBooleanResult;b._addTask(d)});return d.promise};
Dynamsoft.PdfWriter.prototype.writePdf=function(a){var b=this._createTask("GetPdfContent");b.params.returnType=a?Dynamsoft.Enum_ReturnType.RT_BINARY:Dynamsoft.Enum_ReturnType.RT_AUTO;b.handleResult=this._handleImageData;return this._addTask(b)};Dynamsoft.pdf=Dynamsoft.pdf||{};Dynamsoft.pdf.IsModuleInstalled=function(){return Dynamsoft.isWasmSupport()?Dynamsoft.WasmEnv.pdfReader.status==Dynamsoft.conststring.initReady&&Dynamsoft.WasmEnv.pdfWriter.status==Dynamsoft.conststring.initReady:!1};
Dynamsoft.WasmEnv.getLicenseInfo=function(a,b,d){Dynamsoft.WasmEnv.productKey!=a&&(Dynamsoft.WasmEnv.productKey=a,Dynamsoft.WasmEnv.licMode=void 0!=b?b?1:0:0,Dynamsoft.WasmEnv.uuid=void 0!=d?d:"",Dynamsoft.WasmEnv.licensePromise={},Dynamsoft.WasmEnv.licensePromise.promise=new Promise(function(a,b){Dynamsoft.WasmEnv.licensePromise.resolve=a;Dynamsoft.WasmEnv.licensePromise.reject=b;var c=new Dynamsoft.Imagecore(Dynamsoft.WasmEnv.productKey);c.getLicenseInfo().then(function(b){c.terminate();a(b)},function(a){c.terminate();
b(a)})}));return Dynamsoft.WasmEnv.licensePromise.promise};Dynamsoft.WasmEnv.getMemoryUsed=function(){var a=Dynamsoft.WorkerPool.Instance;return a&&!a.terminated?a.getMemoryUsed():{}};Dynamsoft.WasmEnv.getWasmNames=function(){for(var a=[],b=$jscomp.makeIterator(Dynamsoft.WasmEnv.moduleNames),d=b.next();!d.done;d=b.next())d=d.value,a.push(Dynamsoft.WasmEnv[d].prefixName+Dynamsoft.WasmEnv[d].ver+Dynamsoft.conststring.wasmExtension);return a};
